# ================================================
# Auto-generated BDD Feature File
# Generated by: BDD Agent (LangChain + Claude)
# ================================================

Feature: User Login and Authentication

  As a registered user
  I want to securely log in to the application
  So that I can access my personalized account and data

Background:
  Given the system has the following users registered:
    | email                | password     | is_locked |
    | user@example.com     | SecurePass12 | false     |
    | locked@example.com   | ValidPass99  | true      |
    | unlocked@example.com | Locked1234   | true      |

  And the lockout policy allows 3 failed attempts before locking an account
  And the lockout duration is 15 minutes
  And session timeout is 30 minutes

Scenario: Successful login with valid credentials
  @smoke
  Given I am on the login page
  When I enter my email "user@example.com"
  And I enter my password "SecurePass12"
  And I click "Login"
  Then I should be successfully logged in
  And I should see the dashboard

Scenario: Failed login with invalid credentials shows descriptive error
  Given I am on the login page
  When I enter my email "user@example.com"
  And I enter my password "WrongPassword1"
  And I click "Login"
  Then I should see an error message: "Invalid email or password. Please try again."
  And I should not be logged in

Scenario: Account lockout after 3 consecutive failed login attempts
  @regression
  Given I am on the login page
  When I attempt to log in with invalid credentials 3 times:
    | email            | password      |
    | user@example.com | WrongPass1    |
    | user@example.com | WrongPass2    |
    | user@example.com | WrongPass3    |
  Then I should see an error message: "Account temporarily locked due to multiple failed login attempts."
  And my account should be marked as locked in the system
  And I should not be able to log in with valid credentials for this account

Scenario: Unlocking account after lockout period expires
  @regression
  Given the account "locked@example.com" is currently locked
  When 15 minutes have elapsed since lockout
  Then I should be able to log in with valid credentials

Scenario: Reset password request via registered email
  @positive
  Given I am on the login page
  When I click "Forgot password?"
  And I enter my registered email "user@example.com"
  And I click "Send reset link"
  Then I should see a confirmation: "Password reset link sent to your email."
  And an email with reset instructions should be sent to "user@example.com"

Scenario: Password reset fails for unregistered email
  Given I am on the login page
  When I click "Forgot password?"
  And I enter an unregistered email "unknown@example.com"
  And I click "Send reset link"
  Then I should see a message: "If the email exists, a reset link will be sent."
  And no email should be sent (system does not confirm email existence)

Scenario: Password reset token is valid and updates password
  Given I have a valid password reset token for "user@example.com"
  When I visit the password reset URL with the token
  And I enter a new password "NewSecure1"
  And I confirm the password change
  Then my password should be successfully updated
  And I should be able to log in with "NewSecure1"

Scenario: New password must meet complexity requirements
  Given I am on the password reset page with a valid token
  When I enter an invalid password "weakpass"
  And I try to confirm the password change
  Then I should see an error: "Password must be at least 8 characters, include 1 uppercase letter, and 1 number."

Scenario: Password reset token expires after use or timeout
  @edge
  Given I have an expired password reset token
  When I visit the password reset URL with the token
  Then I should see: "This password reset link is no longer valid."
  And I should not be able to change the password

Scenario: Session expires after 30 minutes of inactivity
  @regression
  Given I am logged in and my session is active
  When 30 minutes of inactivity have passed
  Then I should be automatically logged out
  And when I try to access a protected page, I should be redirected to the login page

Scenario: Session remains active during activity
  Given I am logged in
  When I make a request to the server within 30 minutes
  Then my session should remain active and I should retain access

Scenario Outline: Password complexity validation — minimum length and character types
  @negative @password
  Examples:
    | password         | expected_error_message                            |
    | short123         | "Password must be at least 8 characters."        |
    | alllowercase1    | "Password must include at least 1 uppercase letter." |
    | AllLowercase1    | "Password must include at least 1 number."       |
    | AllLowercaseNoNumber | "Password must include at least 1 number." |
    | UPPERCASE123     | "Password must include at least 1 uppercase letter." |
    | AllUPPER123      | "Password must include at least 1 uppercase letter." |

  Given I am on the login or password change page
  When I enter "<password>" as my password
  And I attempt to log in or confirm password
  Then I should see error message: "<expected_error_message>"

Scenario Outline: Login attempts with valid and invalid credentials
  @negative
  Examples:
    | email               | password         | expected_error                     |
    | invalid@user.com    | SecurePass12     | "Invalid email or password."       |
    | user@example.com    | wrongpass        | "Invalid email or password."       |
    |                     | SecurePass12     | "Email is required."               |
    | user@example.com    |                  | "Password is required."            |

  Given I am on the login page
  When I enter email "<email>" and password "<password>"
  And I click "Login"
  Then I should see error message: "<expected_error>"
  And I should not be logged in